### ISSUE TITLE
A problem with the alignment of the ranges to the texts

### ISSUE THREAD

**Issue by asher-stern** [Maluuba/newsqa#12]
Hi.
I encounter a problem regarding the alignment of the character-ranges to the actual text.

I have downloaded the stories from [http://cs.nyu.edu/~kcho/DMQA/](http://cs.nyu.edu/~kcho/DMQA/)
I have downloaded the CSV dataset from: [https://datasets.maluuba.com/NewsQA/dl](https://datasets.maluuba.com/NewsQA/dl)

The problem is: the character ranges specified in the CSV seem to be misaligned with the text.

For example, for the first question, “What was the amount of children murdered?”, the specified (and validated) range is 294:297. However, looking at the text, the characters 294 – 297 are “ict” of the word “victims”, which is four characters after the correct span “19”.

Similarly, for the third question, “who did say South Africa did not issue a visa on time?”, one of the validated answers is at range 839:853.
However, looking at the text (./cnn/stories/c65ed85800e4535f4bbbfa2c34d7d9630358d303.story), the specified range corresponds to “n said.  Visa “. This is several characters after the intended answer, “his spokesman “ (whose characters' range is actually 827:841).

This happens in almost every answer.

I ran the python script in this respository, which generated the file combined-newsqa-data-v1.csv.
I looked at that file, which contains the story-text itself. It contains some extra quotes (because of the CSV format), so, taking those extra characters into account changes the covered string. But it is still incorrect.

Could you please help me with this? It seems that I missed something, but I don't know what.

Thanks.

**Comment by xingdi-eric-yuan** [comment]
Hey @asher-stern , there might be some weird characters exist in the char-level thing, but please check the final generated file, i.e. "newsqa-data-tokenized-v1.csv", in which file the above issues should be fixed, and note the spans are in token level. 
I checked the two examples you mentioned, they are fine in the tokenized file:

```
**id:** ./cnn/stories/c65ed85800e4535f4bbbfa2c34d7d9630358d303.story:
**question:** who did say South Africa did not issue a visa on time ?
**answer span:** 23:26
**corresponding tokens in document:** Archbishop Desmond Tutu

**id:** ./cnn/stories/42d01e187213e86f5fe617fe32e716ff7fa3afc4.story:
**question:** What was the amount of children murdered ?
**answer span:** 60:61
**corresponding tokens in document:** 19
```
In case you were using an legacy version of the preprocessing scripts, please re-run the current version.
Please let me know if you have further question 😸

**Comment by asher-stern** [comment]
Hi.
Thanks for the answer.
I have located the file `newsqa-data-tokenized-v1.csv` and the token-indexes look fine.

However, that file lacks the field "validated_answers". Thus, correct and incorrect answers cannot be distinguished from each other.

**Comment by xingdi-eric-yuan** [comment]
Yes, in the tokenized data, we only keep the "correct" answer which have human agreement.

**Comment by juharris** [comment]
Closing since newsqa-data-tokenized-v1.csv has the right text for tokenized data.
combined-newsqa-data-v1.csv has the right text for answer_char_ranges.
Dataset description updates to clarify this in #13
