### ISSUE TITLE
Problem with csv columns after splitting data into dev,train,test

### ISSUE THREAD

**Issue by raspberryjoy** [Maluuba/newsqa#16]
Hello,
I have tokenized and split the dataset into train, dev, and test, and all tests (python -m unittest discover) pass without any errors. But the slitted dataset doesn't seem correct. See for example next the first couple of lines from dev.csv file.

story_id,story_text,question,answer_token_ranges
68:97|63:97|None,"30,45,64,99,132,155,171,200,251,273,299,313,331,368,401,427,454,479,509,518",13:17,./cnn/stories/d191e20468fc7675fcfa55c33fab1e65405740a0.story

The columns don't match with the data and this is also the case for the test/train.csv files.

**Comment by juharris** [comment]
Thanks for the feedback. I'll take a look in the next few days.

**Comment by raspberryjoy** [comment]
I think that in simplify.py the correct order should be the following   

res.append({"story_id": row[6],
                        "story_text": row[7],
                        "question": row[4],
                        "answer_token_ranges": row[1]})

**Comment by juharris** [comment]
I made the code more robust and it should be fine now.
I guess the code worked for me because of how Python values were being ordered in dicts.

**Comment by prathusha94** [comment]
@juharris I just cloned the repo again and compiled everything to create the dev , train and test csv files. I'm still getting the same error that the key "answer_char_ranges" is not found (reference  https://github.com/davidgolub/QuestionGeneration/issues/2#issue-288379356 ) 
Am I missing something here ?
In one of your posts, you mentioned that "answer_char_ranges" can be found in "combined-newsqa-data-*.csv" . So do I need to pick the column "answer_char_ranges" from this and somehow find a way to merge it with the other csv files ?

**Comment by juharris** [comment]
I just noticed from the stack-trace that you're using Python 3. As per our [docs](https://github.com/Maluuba/newsqa#manual-set-up) Python 2 is required for the manual setup. Sorry! - that's why we have the Docker instructions so that you can prepare the dataset and then use it with whatever you need.

If you don't need the tokenized data then I suggest that you use the new [JSON format](https://github.com/Maluuba/newsqa#json).
