### ISSUE TITLE
answer_char_ranges is missing 

### ISSUE THREAD

**Issue by yexing99** [Maluuba/newsqa#18]
Hi

I tried the repo but the output cvs files only has the following fields ("story_id,story_text,question,answer_token_ranges")  and missing the field " answer_char_ranges " 

Is there a particular reason?

Thanks

**Comment by juharris** [comment]
They were removed from the tokenized version because they aren't reliable in the tokenized version.

The description now shows where to get `answer_char_ranges` from: https://github.com/Maluuba/newsqa#data-description
(see combined-newsqa-data-*.csv)
