### ISSUE TITLE
newsQA data not downloading from site...

### ISSUE THREAD

**Issue by deora786** [Maluuba/newsqa#27]
I know the problem is related to the website(https://datasets.maluuba.com/NewsQA/dl), but following error is coming when I try to download the data.

<Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:bbadd39a-401e-011a-26a9-c2051b000000
Time:2019-02-12T08:07:07.3735366Z</Message></Error>

Please help me download the data or suggest other sources to get it..

**Comment by juharris** [comment]
Thanks for reporting this. I can confirm that it happens for me too.  I'll look into it.

**Comment by juharris** [comment]
Should work now.
Thanks again for pointing that out!
