### ISSUE TITLE
where can i get the json formatted dataset?

### ISSUE THREAD

**Issue by yuchenlin** [Maluuba/newsqa#32]
Hi,

I could only download the CSV data from the link. Am I missing any info?

**Comment by juharris** [comment]
I guess you figured it out but for anyone else coming across this:
As the README.md says, "The code in the repo is used to compile the dataset since it cannot be made directly available due to legal reasons."
To compile the JSON dataset: https://github.com/Maluuba/newsqa#recommended-docker-set-up
