### ISSUE TITLE
Can't find the open dialogue dataset ?

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [Maluuba/newsqa#34]
I need to download the open dialogue dataset.
The link which is shared for the open dialogue dataset doesn't seem to be working.
Can you please share it some other way?
Thank you.

**Comment by juharris** [comment]
I'm not sure which dataset you mean. Is that dataset for another project? Information on getting the datasets for this project can be found here: https://github.com/Maluuba/newsqa#requirements and in the linked pages for that section.
