### ISSUE TITLE
Metrics in NewsQA

### ISSUE THREAD

**Issue by YeDeming** [Maluuba/newsqa#35]
Hi, 

I am confused about the metrics of the NewsQA. In the paper, you use the script for SQuAD to compute the F1 and EM.

NewsQA has the consensus answer and three annoated answesr. Whether you compute the F1 with single consensus answer or report the maximum score with three annoated answers.

And do you discard the bad question or unanswerable question?

Thanks, looking for your reply!

Best,
Deming

**Comment by juharris** [comment]
Does any of the discussion in #8 help?
