### ISSUE TITLE
Docker running time on Macbook?

### ISSUE THREAD

**Issue by AnthonyHein** [Maluuba/newsqa#37]
Hi,

I am a student at Princeton University attempting to use newsqa for a final project for a natural language processing class.

I have followed the instructions up to (and including) the following command:

```
docker run --rm -it -v ${PWD}:/usr/src/newsqa --name newsqa maluuba/newsqa
```

However, it has been running for quite some time ( > 2 hours) and occasionally (~ once every half hour) giving me warnings of the following type:

```
Apr 12, 2021 5:56:00 PM edu.stanford.nlp.process.PTBLexer next
WARNING: Untokenizable: ‬ (U+202C, decimal: 8236)
```

**How long should I expect this to run? Is this normal? Should I seek alternate methods of executing this command?**

Thank you in advance for your time and consideration.

Best,
Anthony Hein

**Comment by juharris** [comment]
Weird. It could because your machine/Docker VM doesn't have enough memory. There are ways to increase it. Let me know if you can't figure it out and I could try to help.

**Comment by AnthonyHein** [comment]
Thank you for your prompt response.

I have increased the memory available to Docker to 4GB as suggested and am rerunning the command.

Are the warnings what is weird or is the running time what is weird?

**Comment by juharris** [comment]
Great that should be enough. Sorry for not being clear. The slowness was weird. A few warnings from that tokenizer are normal.

**Comment by AnthonyHein** [comment]
I increased the memory to 4GB but it still ran for several hours and it looks like there still might be a problem.

<img width="813" alt="Screen Shot 2021-04-12 at 5 01 38 PM" src="https://user-images.githubusercontent.com/60723969/114462318-de3cad80-9bb0-11eb-807e-ac4c4234673a.png">

The above are the last few lines at the terminal. I am unsure why the process was killed, is this something that your script does organically or does this indicate an error?

It looks like I do have the `combined-newsqa-data-v1.csv`, `combined-newsqa-data-v1.json`, and `maluuba/newsqa/newsqa-data-tokenized-v1.csv` files which seems to be the desired result so maybe it was successful after all?

Thank you for your continued support.

**Comment by juharris** [comment]
I don't think we have anything that would kill it. Maybe something happened to the Docker container?

If you just want to use the JSON and the .json file is valid JSON, then it should be fine to use it.

Running the tests should help confirm if the files are okay. I think this should run the tests:
```
docker run --rm -it -v ${PWD}:/usr/src/newsqa --name newsqa maluuba/newsqa /bin/bash --login -c 'python -m unittest discover .'
```

**Comment by AnthonyHein** [comment]
Unsure why it was previously killed. All tests work and I was able to proceed with splitting the data. Thank you again for your help.

I will note that it still took ~ 2.5 hours even with the increased memory, in case others encounter similar issues.

**Comment by juharris** [comment]
Great! Sorry you had so many issues but thanks for persevering.
