### ISSUE TITLE
Tokenized story text

### ISSUE THREAD

**Issue by ryanpram** [Maluuba/newsqa#38]
Hi, how can i get the tokenized story? in newsqa-data-tokenized-v1.csv only have fields: question, answer_char_ranges , is_answer_absent,is_question_bad,story_text,answer_token_ranges ,sentence_starts.

i need something like tokenized_story_text

Thanks

**Comment by juharris** [comment]
Thanks for trying out NewsQA! Sorry about that, it should be better documented. Looking at the code, it looks like `story_text` has the tokens separated by spaces.

**Comment by ryanpram** [comment]
ahh i see, thank you @juharris .
